function ppOptions = ppSelector()
h.f = figure('units','pixels','name','Select Pre-Processing Options','position',[800,480,300,205],...
    'toolbar','none','menu','none');

mTextBox = uicontrol('style','text','position',[0,190,200,15]);
set(mTextBox,'String','Select Pre-Processing Options');

% Create yes/no checkboxes
h.c(1) = uicontrol('style','checkbox','units','pixels',...
    'position',[10,30,300,15],'string','Subtract 95%ile Final Frame Value');
h.c(2) = uicontrol('style','checkbox','units','pixels',...
    'position',[120,150,300,15],'string','Use Upper Limit Size Threshold');
h.c(3) = uicontrol('style','checkbox','units','pixels',...
    'position',[120,130,300,15],'string','Use Region Remover');
h.c(4) = uicontrol('style','checkbox','units','pixels',...
    'position',[10,130,110,15],'string','Remove Isolated');
h.c(5) = uicontrol('style','checkbox','units','pixels',...
    'position',[150,10,110,15],'string','Use Kilfoil pre-proc');


h.removeLargeLabel = uicontrol( ...
    'Style','Text', ...
    'Units','pixels', ...
    'Position',[10,170,300,15], ...
    'String','1.) Enter upper limit size threshold (Microns Sq.)');

h.removeLargeInput = uicontrol( ...
    'Style','Edit', ...
    'String','20', ...
    'Units','pixels', ...
    'Position',[10,150,100,15], ...
    'Callback',@removeLarge);

newAUL = 20;

h.diameterLabel = uicontrol( ...
    'Style','Text', ...
    'Units','pixels', ...
    'Position',[10,110,300,15], ...
    'String','2.) Enter Approximate Feature Diameter for DoG (Microns)');

h.diameterInput = uicontrol( ...
    'Style','Edit', ...
    'String','1.2', ...
    'Units','pixels', ...
    'Position',[100,90,100,15], ...
    'Callback',@selectDiameter);

newD = 1.2;

h.thresholdLabel = uicontrol( ...
    'Style','Text', ...
    'Units','pixels', ...
    'Position',[10,70,300,15], ...
    'String','3.) Enter Feature Threshold % After DoG');

h.thresholdInput = uicontrol( ...
    'Style','Edit', ...
    'String','25', ...
    'Units','pixels', ...
    'Position',[100,50,100,15], ...
    'Callback',@selectThreshold);

newT = 25;




    function selectDiameter(~,~)
        % Get value from h.diameterInput textbox
        newD = str2double(get(h.diameterInput,'String'));
    end

    function selectThreshold(~,~)
        % Get value from h.thresholdInput textbox
        newT = str2double(get(h.thresholdInput,'String'));
    end

    function removeLarge(~,~)
        % Get value from h.thresholdInput textbox
        newAUL = str2double(get(h.removeLargeInput,'String'));
    end

% Create OK pushbutton
h.p = uicontrol('style','pushbutton','units','pixels',...
    'position',[40,5,70,20],'string','OK',...
    'callback',@p_call);
uiwait(h.f);


% Pushbutton callback
    function p_call(varargin)
        vals = get(h.c,'Value');
        checked = find([vals{:}]);
        if isempty(checked)
            checked = 'none';
        end
        close;
    end
disp(checked)
disp(newD)
ppOptions{1} = checked;
ppOptions{2} = newD;
ppOptions{3} = newT;
ppOptions{4} = newAUL;
end