function masterHandle = masterGUI
    % Create figure window and GUI handle h
    masterHandle = figure('Position',[50,100,1800,900]);
    
    handles = guihandles(masterHandle);
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%% Choosing image stack file to be analyzed and cell overlay image
    
    handles.chooseExperimentButton = uicontrol( ...
        'Style','pushbutton', ...
        'String','Choose image stack', ...
        'Position',[20,20,150,20], ...
        'Callback',@chooseExperimentButtonCallback);
    
    function chooseExperimentButtonCallback(~,~)
        exp = Experiment;
        
        axes(handles.rawImgAxes)
        imshow(exp.images(:,:,1),[])
        
        noImgs = size(exp.images,3);
        set(handles.rawImgSlider, ...
            'Max',noImgs, ...
            'SliderStep',[1/noImgs,5/noImgs]);
        set(handles.roiImgSlider, ...
            'Max',noImgs, ...
            'SliderStep',[1/noImgs,5/noImgs]);
        
        setappdata(masterHandle,'Experiment',exp);
        guidata(masterHandle,handles);
    end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%% Displaying raw image stack
    
    handles.rawImgAxes = axes(...
        'Units','Pixels',...
        'Position',[350,200,600,600]);
    handles.rawImgSlider = uicontrol( ...
        'Style','slider', ...
        'Min',1,'Max',50, ...
        'Value',1, ...
        'Position',[350,150,600,20], ...
        'Callback',@rawImgSliderCallback);
    handles.rawImgSliderListener = addlistener( ...
        handles.rawImgSlider, ...
        'Value','PostSet',@rawImgSliderCallback);
    handles.rawImgSliderDisplay = uicontrol( ...
        'Style','edit', ...
        'String','1', ...
        'Position',[350,125,600,20], ...
        'Callback',@rawImgSliderCallback);
    
    function rawImgSliderCallback(~,~)
        exp = getappdata(masterHandle,'Experiment');
        thisFrame = round((get(handles.rawImgSlider,'Value')));
        set(handles.rawImgSliderDisplay,'String',num2str(thisFrame));
        axes(handles.rawImgAxes)
        imshow(exp.images(:,:,thisFrame),[])

        guidata(masterHandle,handles);
    end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%% Selecting a region of interest
    
    handles.cropCheckbox = uicontrol( ...
        'Style','checkbox', ...
        'String','Select ROI', ...
        'Position',[20,50,150,20], ...
        'Callback',@cropCheckboxCallback);
    handles.roiImgAxes = axes(...
        'Units','Pixels',...
        'Position',[1000,200,600,600]);
    handles.roiImgSlider = uicontrol( ...
        'Style','slider', ...
        'Min',1,'Max',50, ...
        'Value',1, ...
        'Position',[1000,150,600,20], ...
        'Callback',@roiImgSliderCallback);
    handles.roiImgSliderListener = addlistener( ...
        handles.roiImgSlider, ...
        'Value','PostSet',@roiImgSliderCallback);
    handles.roiImgSliderDisplay = uicontrol( ...
        'Style','edit', ...
        'String','1', ...
        'Position',[1000,125,600,20], ...
        'Callback',@roiImgSliderCallback);
    
    function cropCheckboxCallback(~,~)
        checkStatus = get(handles.cropCheckbox,'Value');
        if checkStatus == 1 % checked
            handles.r = imrect(handles.rawImgAxes);
            handles.r.addNewPositionCallback(@roiImgSliderCallback)
        else
            delete(handles.r)
        end
        
        guidata(masterHandle,handles);
    end
    function roiImgSliderCallback(~,~)
        exp = getappdata(masterHandle,'Experiment');
        
        roiBounds = round(getPosition(handles.r));
        noImgs = size(exp.images,3);
        roi = zeros(roiBounds(4)+1,roiBounds(3)+1,noImgs);
        for i = 1:noImgs
            newImg = imcrop(exp.images(:,:,i),roiBounds);
            roi(:,:,i) = newImg;
        end
        
        thisFrame = round((get(handles.roiImgSlider,'Value')));
        set(handles.roiImgSliderDisplay,'String',num2str(thisFrame));
        axes(handles.roiImgAxes)
        imshow(roi(:,:,thisFrame),[])

        guidata(masterHandle,handles);
        setappdata(masterHandle,'ROI',roi);
        setappdata(masterHandle,'ROIBounds',roiBounds);
    end
end