function cleanOld(directory)
%%
if nargin == 1
    cd(directory)
end

oldList = {'3DnormalData.mat'...
    ;'DataRaw.mat'...
    ;'DataShear.mat'...
    ;'feature2Doutput.mat'...
    ;'fitSurface.mat'...
    ;'XY Disp Data.mat'...
    ;'rOrginal.mat'...
    ...
    ;'X-Displacement Histogram.png'...
    ;'Y-Displacement Histogram.png'...
    ;'XY-Displacement Histogram.png'...
    ;'Z-Displacement Histogram.png'...
    ...
    ;'ErrorHistNoStress.tif'...
    ;'HistDisplacements.tif'...
    ...   
    ;'Debug Image Spectral.tif'...
    ;'Fluorescent Overlay Spectral.tif'...
    ;'Transmitted Overlay Spectral.tif'...     
    };

for i = 1:size(oldList,1)
    clear loc strL current
    files = dir;
    for k = 1:length(files)
        current=files(k).name;
        strL = length(oldList{i,1});
        if length(current)>=strL
            chk(k)=strcmp(current(end-(strL-1):end),oldList{i,1});
        else
            chk(k) = 0;
        end
    end
    
    loc=find(chk);
    if size(loc,2) >0
    delete (files(loc(1)).name);
    end
end

oldFolders = {'HeatMaps';'Profile Data'};
for i = 1:size(oldFolders,1)
cleardir = rmdir(oldFolders{i,1},'s');
end

end